#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Jan 28 16:00:36 CST 2026
maven-metadata-aliyunmaven.xml.error=
maven-metadata-aliyunmaven.xml.lastUpdated=1769587236043
maven-metadata-huaweicloud.xml.error=
maven-metadata-huaweicloud.xml.lastUpdated=1769587236033
