server:
  port: 48083

spring:
  application:
    name: yudao-module-detection-server
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
knif4j:
  enable: false
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

grpc:
  server:
    port: 9090

yudao:
  web:
    admin-ui:
      url: http://localhost:48080/admin-ui
  detection:
    netty-port: 9999
    data-port: 9998
    flink-parallelism: 1
    filter-window-ms: 5000
    anomaly-threshold: 3.0
    tdengine-batch-size: 1000
    tdengine-batch-interval: 200
    tdengine-url: jdbc:TAOS-RS://127.0.0.1:6041/yudao_detection
